DB_URL: jdbc:mysql://localhost:3306/Echo?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
DB_USERNAME: DB
DB_PASSWORD: Mysqldb#1

JWT_SECRET: Y3ZwPZLtyoxS/nbfuKvaxfOvyKcCPVzj/1U/xlCcFeraRLrd1b9zL7OrOos+9Gdy


SPRING_PROFILES_ACTIVE: prod

app:
  security:
    public-urls:
      - /login
      - /register
      - /saveuser
      - /css/**
      - /js/**
      - /api/v1/auth/send-otp
      - /api/v1/auth/verify-otp
      - /api/v1/auth/refresh
      - /actuator/health
      - /ws/**
      - /favicon.ico
      - /api/v1/auth/me